name: fast_cached_network_image_plus
description: "A Flutter package that extends the functionality of
Fast Cached Network Image to cache network images quickly without native dependencies.
This package introduces enhanced features,
 allowing you to save images by URL along with a unique ID, ensuring that even
 if the URL changes, the image can still be cached effectively. With built-in loaders,
  error handling, and smooth fade transitions, it offers a seamless image caching experience."
version: 0.0.3
homepage: https://pub.dev/packages/fast_cached_network_image_plus
repository: https://github.com/iManYarahmadi/fast_cached_network_image_plus

topics:
  - cache
  - image
  - photo
  - download
  - network
  
environment:
  sdk: '>=2.18.0 <3.24.3'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  hive_flutter: ^1.1.0
  uuid: ^4.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
